sudo: false

language: ruby
rvm:
- 2.1
cache:
  directories:
  - vendor
before_cache:
- rm -rfv vendor/.installed  # force gems to refresh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer
  - secure: "X3DRF4IOel11IO+BuPy4iMYNKAULzHI5QR1sIIIlOVEPIqkaR25H/VEDNjd9ewTOWLXYDipoeAJ1XTINIQNx5no168rKPBRRKCplsOXoZqrZYVbNOABWYYlIFeG6qBp0M5fOIPODmQ4DkpGOhwvhUbHGaTqt3R6VoSAMeutlNm4="

branches:
  except:
  - gh-pages

install:
- make install

before_script:
  # Replace with the line that travis encrypt-file printed out
  - openssl aes-256-cbc -K $encrypted_c536c1d21137_key -iv $encrypted_c536c1d21137_iv -in .key.enc -out .key -d
  - chmod go-rwx .key
  - eval `ssh-agent -s`
  - ssh-add .key
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - git config remote.origin.url git@github.com:anantshri/manual_verification
  - COMMIT_MESSAGE="Test Commit `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"


script:
- make ci

after_success: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST;
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # Generate HTML
    make build ;
    rm -rf .git ;
    # Rebuild the repository from the generated files and push to GitHub pages
    cd _site ;
    git init ;
    git add . ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub pages" ;
    git push -v -f git@github.com:anantshri/test_jekyll_travisci origin gh-pages
    #git push -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} master:gh-pages ;
  fi